# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  # The `no_space` style enforces that array literals have
  # no surrounding space.

  # bad
  # array = [ a, b, c, d ]
  # array = [ a, [ b, c ]]

  # good
  # array = [a, b, c, d]
  # array = [a, [b, c]]
  EnforcedStyle: no_space
